package com.gen3.recommenderagent.inputparser;

import com.gen3.recommenderagent.domain.Intent;
import com.gen3.recommenderagent.domain.session.Query;

/** The small response shape generated by the AI input parser. */
public class ParsedRequest {

  private boolean personalised;
  private Intent intent;
  private Query query;

  public ParsedRequest() {}

  public boolean isPersonalised() {
    return personalised;
  }

  public void setPersonalised(boolean personalised) {
    this.personalised = personalised;
  }

  public Intent getIntent() {
    return intent;
  }

  public void setIntent(Intent intent) {
    this.intent = intent;
  }

  public Query getQuery() {
    return query;
  }

  public void setQuery(Query query) {
    this.query = query;
  }
}
