package com.gen3.recommenderagent.inputparser;

import com.gen3.recommenderagent.domain.Intent;
import com.gen3.recommenderagent.domain.session.Filter;
import com.gen3.recommenderagent.domain.session.SemanticQuery;

/** The small response shape generated by the AI input parser. */
public class ParsedRequest {

  private Intent intent;
  private SemanticQuery positiveSemanticQuery;
  private SemanticQuery negativeSemanticQuery;
  private Filter filter;

  public ParsedRequest() {}

  public Intent getIntent() {
    return intent;
  }

  public void setIntent(Intent intent) {
    this.intent = intent;
  }

  public SemanticQuery getPositiveSemanticQuery() {
    return positiveSemanticQuery;
  }

  public void setPositiveSemanticQuery(SemanticQuery positiveSemanticQuery) {
    this.positiveSemanticQuery = positiveSemanticQuery;
  }

  public SemanticQuery getNegativeSemanticQuery() {
    return negativeSemanticQuery;
  }

  public void setNegativeSemanticQuery(SemanticQuery negativeSemanticQuery) {
    this.negativeSemanticQuery = negativeSemanticQuery;
  }

  /** Returns exact language, duration, and count constraints from the parser. */
  public Filter getFilter() {
    return filter;
  }

  /** Stores parsed constraints so retrieval can build Qdrant payload filters. */
  public void setFilter(Filter filter) {
    this.filter = filter;
  }
}
