package com.gen3.recommenderagent.inputparser;

import com.gen3.recommenderagent.domain.Intent;
import com.gen3.recommenderagent.domain.session.MustInclude;
import com.gen3.recommenderagent.domain.session.MustNotInclude;
import com.gen3.recommenderagent.domain.session.SemanticQuery;

/** The small response shape generated by the AI input parser. */
public class ParsedRequest {

  private Intent intent;
  private SemanticQuery positiveSemanticQuery;
  private SemanticQuery negativeSemanticQuery;
  private MustInclude mustInclude;
  private MustNotInclude mustNotInclude;
  private Integer bookCount;

  public ParsedRequest() {}

  public Intent getIntent() {
    return intent;
  }

  public void setIntent(Intent intent) {
    this.intent = intent;
  }

  public SemanticQuery getPositiveSemanticQuery() {
    return positiveSemanticQuery;
  }

  public void setPositiveSemanticQuery(SemanticQuery positiveSemanticQuery) {
    this.positiveSemanticQuery = positiveSemanticQuery;
  }

  public SemanticQuery getNegativeSemanticQuery() {
    return negativeSemanticQuery;
  }

  public void setNegativeSemanticQuery(SemanticQuery negativeSemanticQuery) {
    this.negativeSemanticQuery = negativeSemanticQuery;
  }

  public MustInclude getMustInclude() {
    return mustInclude;
  }

  public void setMustInclude(MustInclude mustInclude) {
    this.mustInclude = mustInclude;
  }

  public MustNotInclude getMustNotInclude() {
    return mustNotInclude;
  }

  public void setMustNotInclude(MustNotInclude mustNotInclude) {
    this.mustNotInclude = mustNotInclude;
  }

  public Integer getBookCount() {
    return bookCount;
  }

  public void setBookCount(Integer bookCount) {
    this.bookCount = bookCount;
  }
}
