services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: recommender
      POSTGRES_USER: recommender
      POSTGRES_PASSWORD: recommender
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: