# ============================================================
# APPLICATION
# ============================================================

spring.application.name=RecommenderAgent
server.port=8080

# allows virtual threads so one thread can handle multiple requests
spring.threads.virtual.enabled=true


# ============================================================
# POSTGRESQL
# ============================================================

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/recommender}
spring.datasource.username=${POSTGRES_USERNAME:recommender}
spring.datasource.password=${POSTGRES_PASSWORD:recommender}

# CHANGE "update" TO "validate" in production (so it does not create tables and only validates
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


# ============================================================
# REDIS
# ============================================================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}


# ============================================================
# SOLR
# ============================================================

solr.url=${SOLR_URL}
solr.collection=${SOLR_COLLECTION:combinedbooks}
solr.username=${SOLR_USERNAME}
solr.password=${SOLR_PASSWORD}
solr.vector-field=${SOLR_VECTOR_FIELD:embedding}
solr.embedding-dimension=${SOLR_EMBEDDING_DIMENSION:1536}
solr.embedding-index-on-startup=${SOLR_EMBEDDING_INDEX_ON_STARTUP:true}
solr.embedding-index-page-size=${SOLR_EMBEDDING_INDEX_PAGE_SIZE:100}


# ============================================================
# AI
# ============================================================

ai.api-key=${AI_API_KEY}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=${SOLR_EMBEDDING_DIMENSION:1536}
spring.ai.retry.max-attempts=3
