# ============================================================
# APPLICATION
# ============================================================

spring.application.name=RecommenderAgent
server.port=8080

# allows virtual threads so one thread can handle multiple requests
spring.threads.virtual.enabled=true


# ============================================================
# POSTGRESQL
# ============================================================

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/recommender}
spring.datasource.username=${POSTGRES_USERNAME:recommender}
spring.datasource.password=${POSTGRES_PASSWORD:recommender}

# CHANGE "update" TO "validate" in production (so it does not create tables and only validates
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


# ============================================================
# REDIS
# ============================================================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}


# ============================================================
# SOLR
# ============================================================

solr.url=${SOLR_URL}
solr.username=${SOLR_USERNAME}
solr.password=${SOLR_PASSWORD}


# ============================================================
# AI
# ============================================================

ai.api-key=${AI_API_KEY}